### ISSUE TITLE
Why is it implemented with delegateType as bytes32, but docs show string?

### ISSUE THREAD

**Issue by davekaj** [uport-project/ethr-did-registry#30]
Hey, quick question I was hoping someone could answer

The README shows delegate type to be `string`, but the implementation has it as `bytes32`,

Then it is also hashed in the functions. So if I wanted to use the delegate type as `"raiden"`, I would need to pass it as a bytes32, so it seems like I should hash it before I pass it to convert it to `bytes32`. But then it gets hashed again, so it is the double hash of the string `"raiden"`.

Just hoping for some clarity of what I should be passing into the functions for delegate type. Thanks! 😊

**Comment by mirceanis** [comment]
It was switched from `string` to `bytes32` a long time ago, primarily for gas cost reasons it seems (see #2) but the readme was never updated for it.

As for the second question, you don't need to hash it to convert it to `bytes32`, there is a helper method for that called [`stringToBytes32`](https://github.com/uport-project/ethr-did-registry/blob/93bc2c042806281adb6fac6d70dd51478a130b78/test/ethereum_did_registry.js#L63).
It takes the byte representation of the string and pads it with zeroes up to 32 bytes or truncates it if it's longer. You cannot use strings that are longer than 32 characters long (or fewer if you use non-ASCII characters).

**Comment by mirceanis** [comment]
@davekaj also check out [ethr-did-resolver](https://github.com/decentralized-identity/ethr-did-resolver) (which was donated to DIF) to see how the registry is being used.
