### ISSUE TITLE
Safety of using ecrecover() function to verify the digital signature

### ISSUE THREAD

**Issue by praveensankar** [uport-project/ethr-did-registry#40]
Hello,

I was checking the smartcontract "EthereumDIDRegistry" deployed in the mainnet. In the checksignature() function (line no 50) ecrecover() function is used to verify the digital signature and get the address of the signer. When i tried to understand how that function works, i have come across article which states that it's not recommended to use the ecrecover() function in the production environment.  They recommended to use the EIP712 standard. Maybe you guys might wanna check this out and see if it critical or not.

**Comment by mirceanis** [comment]
ecrecover is perfectly normal for on-chain calculation of the signer of a message.
EIP712 is a standard for serializing and signing a typed data object. The actual ECC signature is still a Secp256k1 signature which means that on-chain verification implies the use of ecrecover.

I suspect you may be confusing ecrecover with personalSign. It is indeed recommended to use Eip712 over personalSign.

Please check your sources again and reopen ithis issue if you still see a problem.
