### ISSUE TITLE
Error at eth resolver

### ISSUE THREAD

**Issue by anotherrohit** [uport-project/ethr-did-registry#42]
I see this error on the resolver verifier end when I try to verify the DID created by the issuer on identifier 0xabcabc03e98e0dc2b855be647c39abe984193675

Below is the error,
unable to resolve did document for did:ethr:0xabcabc03e98e0dc2b855be647c39abe984193675: unknownnetwork

the did resolver does not have a configuration for network: mainnet

I have already signed up using the projectid on the verifier. Can you please help in finding the workaround for this?

**Comment by mirceanis** [comment]
Can you share the configuration you are using?

**Comment by andresobandoalfaro** [comment]
Hi @anotherrohit  @mirceanis, I resolved this by downgrading the `ethr-did-resolver` package to the version `^3.0.3`.  Hope it helps to you : )

**Comment by mirceanis** [comment]
I would not recommend that since that version no longer complies with the spec and so is incompatible with many other tools.

This is a configuration issue. Please share your config (while masking any private values), so we can find a solution

**Comment by mirceanis** [comment]
That sounds about right, thank you for your reply.

@anotherrohit, I'm closing this as it seems to not be a bug. If you still can't make it work, please share your config and reopen.
