### ISSUE TITLE
Hi!How to view the generated DID results after contract 'EthereumDIDRegistry' deployment?

### ISSUE THREAD

**Issue by CrissJordanY** [uport-project/ethr-did-registry#57]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mirceanis** [comment]
You can use the [ethr-did-resolver](https://github.com/decentralized-identity/ethr-did-resolver) library.
