### ISSUE TITLE
Sepolia Deployment

### ISSUE THREAD

**Issue by strumswell** [uport-project/ethr-did-registry#58]
Are you planning on deploying the did:ethr contract on Sepolia with the same eth address you used for the other environments for the sake of constant contract addresses? Might be helpful looking at Goerli being deprecated.

**Comment by nickreynolds** [comment]
this registry has been deployed on Sepolia with address [0x03d5003bf0e79c5f5223588f347eba39afbc3818](https://sepolia.etherscan.io/address/0x03d5003bf0e79c5f5223588f347eba39afbc3818#code). It shares the same address as the other registries released at the same version: linea:goerli and arbitrum:goerli
