### ISSUE TITLE
Create example `Todo list` app and tutorial to showcase eth-did and the registry's functionality

### ISSUE THREAD

**Issue by localredhead** [uport-project/ethr-did-registry#6]
#### Task:

Using the ETH-DID library https://github.com/uport-project/ethr-did, write a skeleton app that interacts with the eth-did-registry https://github.com/uport-project/ethr-did-registry to create a simple Todo list that is stored as part of a DID document.  

For each step of the interaction (generally every function call) we would like to write a tutorial that explains the functionality and how we are proposing it can be used in this context.   It's important to note that this may not be a "real world" solution but rather a solution done for academic purposes to highlight the capabilities.

It would be great to utilize the `expiresIn` functionality mentioned here in order to add expirations to a "todo item" https://github.com/uport-project/ethr-did#set-public-attributes 

#### General flow:

![xpfdrjim48jluog1szrhd7l-za18mwje0hrinrtrmeyqjlwcmnaln6-vfi8v4kmwkaxqxixevyi1sqwokbejjqwgdavtwknlr273wriqvgdamnoo8xsw82fojv2sagkf2--yvpgrr6fvrtlvbzulyt8i5awv952c1tgvwkfewydsg4cflopis6mtb98a7snkw1uilddcp2gunke7m2_f_gxtajqt1eh9zto6cu6vyrwme_mf](https://user-images.githubusercontent.com/152448/41237312-3c4d85c4-6d61-11e8-87e1-8ea862770864.png)

##### Login
<img width="1031" alt="screen shot 2018-06-11 at 12 41 13 am" src="https://user-images.githubusercontent.com/152448/41237440-7b64a18e-6d61-11e8-9765-1cf0dd0a303f.png">

##### User is presented with the TODO list
<img width="1030" alt="screen shot 2018-06-11 at 12 48 30 am" src="https://user-images.githubusercontent.com/152448/41237439-7b4f5d88-6d61-11e8-823b-835e46ab41f1.png">

##### User is adding a new TODO item.
<img width="1030" alt="screen shot 2018-06-11 at 12 56 09 am" src="https://user-images.githubusercontent.com/152448/41237438-7b3cd820-6d61-11e8-8900-570f1aa3a616.png">

**Comment by oed** [comment]
Hm, while there is technically no problem with this idea, I'm not sure that putting application data in the did-registry is something that we want to encurage. The more data that is associated with your DID the longer it's going to take to resolve the DID-registry. 
Perhaps this would be something that ERC780 could be useful for?

**Comment by only1sham** [comment]
Is there any work happening on this ToDo app? It will be really useful to understand the concepts crearly if we can get a sample app like this.

**Comment by SimoneMarrone** [comment]
It will be very helpful to have an example like this showing these concepts.

**Comment by gdollard** [comment]
Any progress on this? Some end-end examples would be very helpful. I'm finding the partial code snippets very confusing.

**Comment by mirceanis** [comment]
I did not realize this issue existed and I'm sorry it survived this long un-closed.
The DID registry is not meant for this kind of use-case. There's nothing specifically meant to stop people from using it like this but, as @oed [suggested earlier](https://github.com/uport-project/ethr-did-registry/issues/6#issuecomment-396516272), every attribute associated with an address will make the DID document for that address that much harder to resolve.

The registry is meant to hold publicKeys and service endpoints that are relevant for an address as it relates to [DIDs](https://www.w3.org/TR/did-core/); more specifically `did:ethr`. Take a look at the [ethr-did-resolver](https://github.com/decentralized-identity/ethr-did-resolver) to get an idea about how the registry is used off-chain.

@gdollard, @SimoneMarrone, @only1sham please describe in more detail your use-cases, if possible, most likely you don't need to call the registry directly and can solve problems using a library that does if for you. See [ethr-did-resolver](https://github.com/decentralized-identity/ethr-did-resolver) and maybe [ethr-did](https://github.com/uport-project/ethr-did)

**Comment by gdollard** [comment]
@mirceanis thanks for getting back to us anyway. After reviewing ethr-did-resolver (and did-resolver) I understand your point about not needing to directly interact with the registry.
